# Generated by Django 5.2.4 on 2025-08-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillgroup'),
        ),
    ]
