# Generated by Django 5.2.4 on 2025-08-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_skill_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='group',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
