# Generated by Django 5.2.4 on 2025-08-08 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_resource_owner_remove_resource_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
