# Generated by Django 5.2.4 on 2025-08-09 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_videogame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('going_users', models.ManyToManyField(blank=True, related_name='tournaments_going', to=settings.AUTH_USER_MODEL)),
                ('not_going_users', models.ManyToManyField(blank=True, related_name='tournaments_not_going', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
